title: # Github best practices
tagline: # Ten practices to improve the way you collaborate on Github
description: # This course will cover some of the best practices for Github when collaborating with teams

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: Basic Repo    # the name of the repository when it is created for the learner
  repo: basic-template    # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: Setting up a repo to encourage collaboration
- title: # Setting up your repo to encourage collaborators
  description: # A good repository will guide collaborators as they take their first steps in using and contributing to your project
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: Encourage feedback early
# - title: # Encouraging early feedback to ensure a smooth onboarding
#  description: # Codifying what to do when things don't work as expected can go a long way to creating a positive onboarding experience even when things go wrong
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: Automate responses to feedback
# - title: # Automate responses to feedback
#  description: # Automation can help reinforce positive responses to giving feedback and set expectations for next steps
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: Create a path to contribution
# - title: # Create a path to contribution
#  description: # Making it easy to contribute changes will pay dividends later
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: Recognize contributors
# - title: # Recognize contributors for their efforts
#  description: # Automation around forks, pull requests and merges to recognize the efforts of contributors
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

